### ISSUE TITLE
SCP-914 does not work with Realistic Item Drops

### ISSUE THREAD

**Issue by Terra-B-Welch** [ConnorTron110/SCP-Lockdown-Issues#13]
Items dropped into SCP-914 do not work when using the Realistic Item Drops mod. While not game breaking, it does make 914 useless.
https://www.curseforge.com/minecraft/mc-mods/realistic-item-drops

**Comment by ConnorTron110** [comment]
I've had a look and it seems that 914 doesn't detect the item as that mod uses Custom Entities for its rendering (Instead of overriding the rendering of the item class itself which would have been smarter). I See the issue clearly and know ways to fix it, Expect a fix on 2.4.1 :D

**Comment by Terra-B-Welch** [comment]
it was in singleplayer.

**Comment by Terra-B-Welch** [comment]
I guess I just don't know how to properly use 914 then.

**Comment by ConnorTron110** [comment]
Quite possible, I will close this issue now and remove the bug label, as it could be due to the config. If you encounter this again with a different/same mod, make a new issue, Thanks!
