### ISSUE TITLE
SCP-049-2 Texture Glitch 

### ISSUE THREAD

**Issue by MUSlC** [ConnorTron110/SCP-Lockdown-Issues#15]
I have this weird issue where the textures of SCP 0-49-2 is missing and is somewhat invisible. Here is a photo provided below, SCP 049-2 is the result of being "cured" by 049 but i can only see a entity shadow and yes im using regular forge no optifine or anything. 
![IMG20210815215532_00](https://user-images.githubusercontent.com/88974850/129480904-f93332d3-7b1d-44ae-8978-2225b3b82651.jpg)

`Help`

**Comment by ConnorTron110** [comment]
No Updates on this, will close. If this has a way of being reproduced I will do my best to fix.
