### ISSUE TITLE
Card Reader Doesn't Work On Mohist

### ISSUE THREAD

**Issue by MasterPNJ** [ConnorTron110/SCP-Lockdown-Issues#16]
Recently, the card reader no longer works. When in use, the green light turns on but the door does not open. I broke the door and the card reader, then I put them back but this one still does not work. I am on the latest version of Mohist in 1.12.2 (on server which mixes forge and plugin), I also have the latest version of SCP Lockdown in 1.12.2 and other mods.

Hope you can fix the problem

Edit : The card reader works in solo mode, so it is surely a problem related to Mohist and not a compatibility problem between mod.

**Comment by davis697** [comment]
i tried to figure it out but cant i tried this minecraft:chest/0/veryfine/16/shulker_shell/2/0 what is wrong can you give me the correct one please
