### ISSUE TITLE
SCP-914 custom recipes issue

### ISSUE THREAD

**Issue by Bl4ues** [ConnorTron110/SCP-Lockdown-Issues#18]
I posted a comment on curseforge but then I noticed it was on github as well, so here I am.

First of all, great mod! Really brings together the SCP feel to the minecraft style very well, and works pretty nice with a lot of other SCP mods, but I am experiencing a little problem. I'm working in a small project involving a custom modpack and map and have the SCP-914 in it. I decided to add a lot of custom recipes in the config file, things even from other mods (like SCP-500 turning into SCP-427, for example). And everything seems alright, the recipes appeared in the list and they DO appear in JEI, but when I try to get them into the SCP-914 itself, they don't work. Default recipes still work as intended, but not the custom ones. 

I'm sorry for bothering, I was going to just let it be, but 914 is just a very good SCP for being just decoration. Thank you for your work and attention.

**Comment by davis697** [comment]
i tried to figure it out but cant i tried this minecraft:chest/0/veryfine/16/shulker_shell/2/0 what is wrong can you give me the correct one please
