### ISSUE TITLE
Night Vision goggles cause memory leak?

### ISSUE THREAD

**Issue by Terra-B-Welch** [ConnorTron110/SCP-Lockdown-Issues#22]
For some reason, equipping the night vision goggles for a prolonged period of time causes constant memory dumping, freezing the game frequently, this makes it very hard to use the NV goggles, the issue does not occur unless NV goggles are worn for a long period of time.

**Comment by ConnorTron110** [comment]
I'll give this a check, thanks for the heads up!

**Comment by ConnorTron110** [comment]
Haven't experienced anything after 10 minutes, could you send your PC specs, and possibly say what was happening around you during the freezing of your game?
I know it has been a while but if you could reproduce this again that would be greatly appreciated :)

**Comment by ConnorTron110** [comment]
No responce in almost a year, closing. If anyone has the same issue please let me know.
