### ISSUE TITLE
having problem with mutiplayer

### ISSUE THREAD

**Issue by tantais123** [ConnorTron110/SCP-Lockdown-Issues#23]
when friend join he receive message illegal  item snow layer like this, problem was fix when we remove scp

![image](https://user-images.githubusercontent.com/98269504/155697808-8fd25799-dc34-4f8d-8607-4d4079a10087.png)

**Comment by ConnorTron110** [comment]
Could you send the log when you try to join the server?

**Comment by tantais123** [comment]
if you talking about me, how can i find it

**Comment by ConnorTron110** [comment]
First open your game.
Try to connect to a server.
Close the game.
Go to your games `<directory>/logs/latest.log`

If that doesn't help I found this website that should run through step by step how to find them, https://ecocitycraft.com/forum/wiki/minecraft-client-logs/

**Comment by ConnorTron110** [comment]
I Will close this as this has not been updated, also may not be related to Lockdown, if more information can be provided I will reopen it.
