### ISSUE TITLE
SCP-096 crashes game when a Custom NPC Views its face

### ISSUE THREAD

**Issue by scpfan69** [ConnorTron110/SCP-Lockdown-Issues#24]
Ok so, when i had 096 breach containment, a NPC Guard viewed its face,  and after that the game crashed, or just frozed then the screen turned black.

**Comment by scpfan69** [comment]
ok well now it happens anytime a custom npc runs into a scp

**Comment by ConnorTron110** [comment]
Does this custom NPC use a weapon? Specifically Vics Modern Warfare or Techguns?

**Comment by ConnorTron110** [comment]
I've done my own testing on this and it appears to be the type of ammo you use for the weapon of the NPC, nothing to do with Lockdown. If this can be proven wrong, I will reopen and take another look
