### ISSUE TITLE
what is the code to use scp 914 to turn chests into shulker shells

### ISSUE THREAD

**Issue by davis697** [ConnorTron110/SCP-Lockdown-Issues#25]
i tried to figure it out but cant i tried this minecraft:chest/0/veryfine/16/shulker_shell/2/0 what is wrong can you give me the correct one please

**Comment by ConnorTron110** [comment]
This isn't a bug report so I'm going to close this, for future questions related to this I recommend joining our [Discord](https://discord.gg/NGdHJzh)!

However to quickly answer your question you put `shulker_shell` as the ID which isn't the full and correct id. In 1.12.2 all Shulker Boxes have their own unique id as such:
![image](https://user-images.githubusercontent.com/39780128/163653149-9c59ad12-ea13-459b-9228-f55c58e6b0f3.png)
So to get your recipe working correctly it would be `minecraft:chest/0/VERYFINE/16/minecraft:purple_shulker_box/2/0`

Also please don't spam questions into other threads, it's unnecessary, thanks!

**Comment by davis697** [comment]
thank you

________________________________

**Comment by davis697** [comment]
your the best thank you

________________________________
