### ISSUE TITLE
opinion about this mods

### ISSUE THREAD

**Issue by yqminecraftplayer** [ConnorTron110/SCP-Lockdown-Issues#27]
Hi ,I have some opinoin about this mod.

1)upgrade this mod to 1.16.5 version or above.

2)add some npc foundation personal etc:security department,all mtf ,05 council,adminsrative department and sciencist.

3)also add some enemies with the foundation like chaos insurgency

This is all my opinion.

**Comment by ConnorTron110** [comment]
This is your opinion, not a bug report...
But to answer that:

1) Modding is a long-winded process, I'm the only "active" programmer in the team, it will take its time as it's not as easy as 1,2,3 and I also have a lot of external factors going on in my life.
2 & 3) I think the team and I can agree that these will not be added any time soon, we have the 1.16 port to do and this is the least of our priorities.

If you have any further suggestions I recommend saying them on our [Discord](https://discord.gg/NGdHJzh).
I will close this thread as this is not a bug report.
