### ISSUE TITLE
recipe issues

### ISSUE THREAD

**Issue by souless44** [ConnorTron110/SCP-Lockdown-Issues#33]
Recipes, like the gun tech mod are crossed with others and that prevents progression. Without a way to force the pack to produce the proper items, the items from this mod are eliminated completely.

**Comment by ConnorTron110** [comment]
Modders cannot accommodate their mod to avoid conflicts with every other mod in the game. It's simply impossible for me as a developer to know what mods use a recipe. 
Mods like [This](https://www.curseforge.com/minecraft/mc-mods/yarcf) Exist to help with this problem.
I won't be fixing this for the reasons stated above, as if I had to fix it, any new mod that releases with the same recipes, I will have to change it every time.
