### ISSUE TITLE
Issue while wearing telekill armor causes camera drift

### ISSUE THREAD

**Issue by VoidFrost08** [ConnorTron110/SCP-Lockdown-Issues#39]
I found the issue while playing on a multiplayer server, and I tested it to make sure it wasn't caused by any other armor I had from the mod, and I found that specifically with the telekill armor equipped, every 10 to 15 minutes the camera begins to drift randomly in multiple directions and does not stop when it happens and I've found that it only stops drifting when you die, and if the armor is put back on after death, the process repeats after another 10 to 15 minutes has passed.

**Comment by ConnorTron110** [comment]
Hi, thanks for the submission. This is an intended feature of the mod, should make that more apparent but when you take the armor off it does go away, but it does take i think 30 mins or so. If that is not the case, please feel free to reopen the issue and ill be glad to help!
