### ISSUE TITLE
NVG Overlay F4 Bug

### ISSUE THREAD

**Issue by MeoistPickle** [ConnorTron110/SCP-Lockdown-Issues#4]
Version: SCP_Lockdown-1.12.2-2.4.0-hotfix.jar

Hi, the update seemed to have broken the night vision goggles. The goggles don't turn the screen green when N key is pressed, all that happens is the toggle sound effect plays and the chat says the goggles are activated. This also affects SCP-966 "The Sleep Killer," as originally you could only see it when the goggles were toggled. Now you can see 966 when just wearing the goggles on your head, regardless of if the chat says they are activated or not.

**Comment by ConnorTron110** [comment]
Do you have any shaders installed? or have you pressed F4 at all?

**Comment by MeoistPickle** [comment]
No shaders but what will pressing f4 do?

**Comment by ConnorTron110** [comment]
F4, for some reasons disables them. Currently I don't know why, but I will have to look into it a bit later to figure out why it exists.

**Comment by MeoistPickle** [comment]
Ok I’ll look and see if that fixes the issue, I’ll let you know

**Comment by MeoistPickle** [comment]
So I changed some settings with Optifine and now I get the green overlay regardless if the goggles are toggled on or off, they just have to be equipped. F4 disables the overlay only until I click the N key again so maybe Optifine is the issue? This didn't happen before the update though and I had Optifine installed.

![NightVision On](https://user-images.githubusercontent.com/80706369/117205292-105bbc80-adb7-11eb-9e26-ecb300ac4c7c.png)
![NightVision Off](https://user-images.githubusercontent.com/80706369/117205295-118ce980-adb7-11eb-940c-52070bcb3086.png)
![Video Settings](https://user-images.githubusercontent.com/80706369/117205297-118ce980-adb7-11eb-9591-9c72efe68bf5.png)
![Quality Settings](https://user-images.githubusercontent.com/80706369/117205299-12258000-adb7-11eb-9716-538c6c6bf2b9.png)
![Performance Settings](https://user-images.githubusercontent.com/80706369/117205300-12be1680-adb7-11eb-9146-ad0720d7ada6.png)

**Comment by ConnorTron110** [comment]
Hmm, I haven't changed How the goggles work, so it could be a new thing with optifine. Also it being green even when "Off" isn't a bug as it is an intended feature. Thanks for the info, ill look into fixing compatibility issues with Optifine.
