### ISSUE TITLE
SCP-2761 is causing a memory leak

### ISSUE THREAD

**Issue by QuantumAvali** [ConnorTron110/SCP-Lockdown-Issues#6]
I was testing out the new SCPs while using the latest 2.4.0 hotfix and kept running into issues affecting my whole computer. After quite a while of narrowing it all down, it seems the issue was a memory leak in Minecraft being caused by SCP-2761, particularly whenever looking in the general direction of SCP-2761 (so basically whenever it's rendered on screen whether visible at all or not)

**Comment by ConnorTron110** [comment]
I have heard about this issue on multiple occasions, but the word "memory leak" hasn't been said yet. What makes you think its that?
I could write down a few reasons on why, but I would like to hear what made you come to that conclusion.

**Comment by QuantumAvali** [comment]
Well, this first came to my attention when I left the game paused, and after a while, it would crash Minecraft as well as break other programs. Got curious and opened up Task Manager to look at my PC performance while playing, and noticed that RAM usage just kept going up. Even when I only assigned 2 GB RAM to Minecraft, the in-game RAM usage would be fine, but Minecraft itself in Task Manager kept being allocated more RAM until it ate up all 16 GBs. And since it only happened around the new SCPs, I focused on those, narrowing it down until I found SCP-2761 specifically to be the cause

**Comment by ConnorTron110** [comment]
Did you have any other mods running at the time? (Optifine/Performance Mods) And how long would you say it took until it crashed?

**Comment by ConnorTron110** [comment]
I've come back after a massive break and know what the issue is, huge mistake on my end, improper coding strategies was used which is causing this issue. Will fix for next update!

**Comment by ConnorTron110** [comment]
Fix on https://www.curseforge.com/minecraft/mc-mods/scp-lockdown/files/3824589
