### ISSUE TITLE
Compatibility issue between SCP Lockdown and BuildCraft Silicon on server

### ISSUE THREAD

**Issue by RoSirius** [ConnorTron110/SCP-Lockdown-Issues#7]
- Forge Version: 1.12.2 (14.23.5.2855), Server
- SCP Lockdown 2.4.0 
- Any additonal mods: BuildCraft Version 7.99.24.8 (including BuildCraft Silicon)

Was asked to send issue here to see if it can get resolved. Below is the error I have encountered trying to start a server with both mods present.
[The error I received in a text file](https://github.com/BuildCraft/BuildCraft/files/6460995/error.txt)

**Comment by ConnorTron110** [comment]
Confirmed on multiple accounts, Have not taken a deep dive on what could be the issue but I'll update this when I fix it.

**Comment by ConnorTron110** [comment]
Fix on https://www.curseforge.com/minecraft/mc-mods/scp-lockdown/files/3824589
