### ISSUE TITLE
SCP 689 acting weird.

### ISSUE THREAD

**Issue by IISSAAII** [ConnorTron110/SCP-Lockdown-Issues#8]
![2021-05-26_18 57 26](https://user-images.githubusercontent.com/59371019/119745857-aafa6900-be54-11eb-9009-962c3ecbcc38.png)
When I look at 689 my chat gets filled with the message "You spotted SCP-689" but nothing happens after that (Even when I look away).
This happens even when I only have SCP lockdown installed with no config changes.
Forge version is 14.23.5.2855, mod version is 2.4.0 hotfix.

**Comment by ConnorTron110** [comment]
This doesn't seem to be happening for me, are you running on a server?
What's your Mod List?
A Video (If possible showing the bug)
And the latest.log after experiencing the bug.

**Comment by ConnorTron110** [comment]
No updates, closing thread.
