### ISSUE TITLE
Wierd crash on 1.12.2

### ISSUE THREAD

**Issue by joey-lg** [ConnorTron110/SCP-Lockdown-Issues#9]
[crash-2021-06-10_11.37.19-server.txt](https://github.com/ConnorTron110/SCP-Lockdown-Issues/files/6650561/crash-2021-06-10_11.37.19-server.txt)
Keep in mind that I'm using the following mods:
![Capture](https://user-images.githubusercontent.com/62820134/121943171-4e85bd80-cd1f-11eb-87b4-d1ae8819ca2c.PNG)

**Comment by ConnorTron110** [comment]
Not Related to SCP:Lockdown
`scootys_scp_mod:scplabel999` Seems to be causing the issue which comes from the `SCP+Lockdown+Heavy+Expansion` Mod.
Gonna close the ticket as its not related and I cant do anything about it.
